<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="09LogoutAndSessionClear"
    errors="0" failures="1" hostname="" id="" package="09LogoutAndSessionClear" skipped="0"
    tests="1" time="13.88" timestamp="Mon, 25 Jun 2018 20:39:02 GMT">
  
    <testcase name="Logout and Session Clear" classname="09LogoutAndSessionClear" time="13.88" assertions="2">

      <failure message="expected account in url">    at Object.Logout and Session Clear (/Users/Peizer/Documents/EventKitTest/tests/09LogoutAndSessionClear.js:24:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
