<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="09LogoutAndSessionClear"
    errors="0" failures="1" hostname="" id="" package="09LogoutAndSessionClear" skipped="0"
    tests="1" time="12.39" timestamp="Tue, 17 Jul 2018 14:49:05 GMT">
  
    <testcase name="Logout and Session Clear" classname="09LogoutAndSessionClear" time="12.39" assertions="12">

    

    

    

    

    

    

    

    

    

    

      <failure message="expected account in url">    at Object.Logout and Session Clear (/Users/Peizer/Documents/EventKitTest/tests/09LogoutAndSessionClear.js:24:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
